name: vgg_hgru
import_prepath: serrelabmodels.models.vgg_16
import_class: VGG_16
args:
  weight_path: /media/data_cifs/model_weights/vgg16.tar.xz
  load_weights: true 
  freeze_layers: true
  n_layers: 17